version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: alumni_db
      POSTGRES_USER: alumni_user
      POSTGRES_PASSWORD: alumni_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alumni_user -d alumni_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 alumni_backend.asgi:application"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key-change-this
      - DATABASE_URL=postgresql://alumni_user:alumni_password@db:5432/alumni_db
      - REDIS_URL=redis://redis:6379
      - ALLOWED_HOSTS=localhost,127.0.0.1,yourdomain.com
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: ./backend
    command: celery -A alumni_backend worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key-change-this
      - DATABASE_URL=postgresql://alumni_user:alumni_password@db:5432/alumni_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    command: celery -A alumni_backend beat -l info
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key-change-this
      - DATABASE_URL=postgresql://alumni_user:alumni_password@db:5432/alumni_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
